# CI workflow for a Node.js project

name: Node.js CI Pipeline

# Run this workflow on push and pull requests for the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Define jobs in this workflow
jobs:
  # Job to install, test, and build the project
  test-and-build:
    runs-on: ubuntu-latest

    # Define environment variables (example)
    env:
      NODE_ENV: test

    steps:
      # Step 1: Checkout the repository to access the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test

      # Step 5: Build the project
      - name: Build project
        run: npm run build

      # Step 6: Upload build artifacts (example for deployment)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./dist  # Adjust path to where the build outputs are located

  # Example of a separate deployment job (optional)
  deploy:
    runs-on: ubuntu-latest
    needs: test-and-build  # Ensures this job runs after 'test-and-build'
    if: github.ref == 'refs/heads/main' && success()  # Only deploy on main branch after successful build

    steps:
      - name: Deploy application
        run: |
          echo "Deploying the application..."
          # Example deployment commands go here, adjust based on hosting platform
